env:
 global:
   - secure: "kr/jT8EZPVDEOOONszw8UGXhIIYw9JwAUpPb5BbT5Niou6fbZI/z0ATe1J16gyjuJvAP0JEKhGmsnzXRpVud6N51FsjJ9L2aJReLkD9Iyeg7QeIKfRI8bvA71xoShVDFU1RFILf4pjnEO6JeK6tSW060Q3+Fr5hg37oTgK1Hj89I6ibJrp3OnbDALtYjqV8xlElYtQjEkyyhKycgjz3VmE5molii1Dq5Cd0oRAb6J8Lb+hr8pTi9jDXlhVM0iK5l6r14Z6H9xspHOzu1iUJGeRXo4PFuICo79Mmrl+4V+q25olHtIMl4rwhvWOdQ/BwtdUZlefXc/8sUtM9l5kSY4hVc3vWkH4uymZMQgTmVTaukcy0zY9MwoLEZSdrf66pP6rSkUugmtASZIp67VPgxJx7YLgO8FNqhOaKxTTCa7z3Mf0vCJnySMKlmT13nJsjXQaPWel7NhhEGB+GS+E1fWurxe7OV4eK3IJW1Lc7F9kV2bN6BY1dLSR3WAvyzBRWEcEtu17W9DKFFTcISdWYH878pUADRzlraDQGiWLLLLW5Z0B/TN4PHPwU6/8jw0H75n4W2M7FPdPD9MnKSxdmszdplryxHfGk/buaP0NxkDFmacSlTN11VaDNogLonYwzK7/tJ+kfGy+4Km6ob8TmxUgf/40datctiag/66nIixQM="
   - secure: "WXdva70VPBsdT4Am+J6iJuHmvvWT9/o+hdXeaXvAk1WSMj9TI+QiVlL7BG8ec7QqWR6u6TCpOWNKDWpFQFMJYBOgDZHRehe68rFFjIPPFOuqLwEY+ZKt7nhxQmw/rGZ5tk1vtxjCsOhw7dyuWM6EhqQmp9nLVE5UZGsGFFX5DXFFwvMIFOilGM6F+alWj3g0DJqqXgly/B2Iv+SSCwBqM8GymUkF6Wt39zAi9XoOUAyllDL1X69pyTnAkWlv4Pg5N9fJUJIX7asaKezk5hvRcjRZOkXn2hzPWaXlF6Pt/pzrAOV7OjR6MfdopPgbh4tJxgv1qmDDwcbxip2k8oraHoWoxzSj4L4bok9Lt3PstwGa8CswUFvvqt0ayHdqXOGOyrK3QkKH3Rm5WCxiYtXF6qxkBMgnK0+vbcOgdygfScnWEcFaHicBjSnr9xTt37fOI7NZsqZgXfVzHH8C02dlLNTFVp6/VPYwbpqbE8E3w5x+8D5dIQUwAw3sUNqprJzMs9REWlvl+GpCGbR76K05SXS7SrXd9UFNH33QyhWz+XlOKZ1zt2xfWXEM3fmaTjf0YjC5Sn99aeNb7qksvWuYNRlp4Q1yaFR3jX86esc+5cUvZY79WKB9aTXTXrQ6HWAq3SPs7Rw3caXpF9xKi7SJs1ZJryVdhcrtFOScsBW2LME="
   - secure: "HCX9pT15QeyZYuW6Bj0lYuPBQx9cdJyan5uNay6guzCs4t9SFzVgBV/jjNHvy1pgufw8DYbjV4rsN3QVfFSQk7yvlpK3+vwc7r7nu5Efxce43T5stZiGVBeb567g3EruO8q3YffvGnIPW+1yNumTpan0GZB6YcVwLnbPizpK20aDzz52rB8WyBsdaIuiN+lNyhzgw+gUr0dW0V+Xy6JEoqcNpnssEPZZcKWj3edHFUu+gbEqHJpkkaX4un8Sxrc6rPF5+LEY9vBj4LXoHtnabRbmzqLX1F4LRA7E2i8D5+C6Wd8XHkvMZ6InlTa9KRR3zwgMoJ+gEaaMIeEQG1IMhYMoMySlMt4ATFD60TnCE9Zul3NC7q4vClKb++D06uiW4uD1UCoTCnw1uIkbAa/xzw+rGN3lWHk0EJwNVWmWZVGlXIV/zTtN0Ib7PXBf5loy13oo2sdMFuJzDSuCaYiaszNtIrQXx9O7O1cJi/6xA7Z60HoLSIgb2qDUDUi97LQIl3lYkdOJTMysBx+I3OGzLA9ZXynDoJ0cicjOaVYtqIv2llq5rJs4kJXsZQynynTrG9NwnE2Bbt6FIrSh8iACyykxNTNUC5AfMS1twu9+h2mn3NEjXasNRhBD+zKp8PCI39X3hPw9eTFxDqYPjPJ9ZGjEKItmP0GKCEfd9eoq5OE="
   - secure: "UypZY0RsxKqOGviekubUr30oJl333bU1djJGGmHQ4fx+ajrtq+FcsowKej0+ikWHdIKmGf0c4GcNfNu/oy1MGSGsWZ3Es6dxryiC1Fe1l0gQDYD8ykSlfOFhIzTlLU0lk85D6w2WgB3Nxo9isluMXaAeyzNbYE1Dsfq9tljkSeryjzAwUQIFdFf/y7mMproagi0HEem5DaZLQT7wILjLbB11s2RymFREHic/pGd3qKmilOSl8XTqX6HR/HadyGWPP8SRbzEZCc/V132mSUMZOwdqzBB5QXufyCHrJRYtnqFcQP9qTo2zOewqv017HY0rV8CpWntk7bfzXB3o3V5cOWr+IdmYxLgpGxTpmsdaSoiOf0a60+gW0jOO7tYH85wqGyQ8GdYRFkeYEvGH919DMcMeHlV9keOAP1OwU2sLN7jU2+iqI0OPSbrJ53/dYga3E9RMhz6o0bmlLYFxKtetCrPsqdOEHXtIt1dGMPiyKTBMVNMxYDRgZu0LntOg49L/76NJyY8YKOU170+2n4WPax0Rn1vcJyX+NCk/2l3uW1bFNgDw4sQIaJ3EiVKSrc2rJHD2cT5cXahTjhSmzs0UaSuXJhUzgxn+054DYRWqcwzKSmPPkU5I6JfLdV0FmvYPhLuK9DtMhv96eHYqj3tB8HqInTCeHX+tLOOqKpzEOdE="

os:
  - linux

language: minimal

services:
  - docker

before_install:
  - docker login --username $DOCKERHUB_USR --password $DOCKERHUB_PWD;
  - docker login --username $REDHAT_USR --password $REDHAT_PWD registry.redhat.io

install:
  - docker build --file d.jboss.Dockerfile --tag juliaaano/rhdm-jboss:latest .
  - docker build --file d.springboot.Dockerfile --tag juliaaano/rhdm-springboot:latest .

before_script:
  - docker-compose up -d --force-recreate rhdm-jboss rhdm-springboot
  - sleep 90

script:
  - POSTMAN_ENV=rhdm-jboss docker-compose run --rm postman
  - POSTMAN_ENV=rhdm-springboot docker-compose run --rm postman

after_success:
  - for i in $(docker images --format "{{.Repository}}:{{.Tag}}" | grep "juliaaano"); do docker push $i; done
