version: '3.3'

services:

  rhdm-jboss:
    image: dockersample/rhdm-jboss:latest
    environment:
      KIE_ADMIN_USER: admin
      KIE_ADMIN_PWD: admin
    ports:
      - target: 8080
        published: 18080
      # - target: 8443
      #   published: 18443
      # - target: 8778
      #   published: 18778
      # - target: 8888
      #   published: 18888

